-- 006_storage_bucket.sql — Supabase Storage bucket for PDFs
--
-- Defense packets and evidence summaries are stored as PDFs in this bucket.
-- Files are private — accessed via signed URLs generated by the app.

INSERT INTO storage.buckets (id, name, public)
VALUES ('scalesafe-files', 'scalesafe-files', false)
ON CONFLICT (id) DO NOTHING;
