import { renderHtmlToPdf } from './pdf-renderer.service';
import type { ExhibitEntry } from './defense-exhibits.service';

/**
 * Renders the defense letter (AI-generated or merchant-edited Markdown text)
 * as a professional PDF with exhibit index.
 */
export const defenseLetterPdfService = {
  async generateLetterPdf(opts: {
    letterText: string;
    merchantName: string;
    clientName: string;
    reasonCode: string;
    disputeAmount: number;
    disputeDate: string;
    caseNumber: string;
    addressee: string;
    defenseId: string;
    exhibits: ExhibitEntry[];
  }): Promise<Buffer> {
    const html = buildLetterHtml(opts);
    return renderHtmlToPdf(html);
  },
};

function esc(s: string): string {
  return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function buildLetterHtml(opts: {
  letterText: string;
  merchantName: string;
  clientName: string;
  reasonCode: string;
  disputeAmount: number;
  disputeDate: string;
  caseNumber: string;
  addressee: string;
  defenseId: string;
  exhibits: ExhibitEntry[];
}): string {
  // Convert Markdown-ish text to basic HTML (headers, bold, paragraphs)
  const letterHtml = (opts.letterText || '')
    .split('\n\n')
    .map(para => {
      let p = esc(para.trim());
      // H3 headers
      p = p.replace(/^### (.+)$/gm, '<h3 style="font-size:14px;font-weight:600;color:#1f2937;margin:12px 0 6px">$1</h3>');
      // H2 headers
      p = p.replace(/^## (.+)$/gm, '<h2 style="font-size:16px;font-weight:600;color:#111827;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin:16px 0 8px">$1</h2>');
      // Bold
      p = p.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
      // List items
      p = p.replace(/^- (.+)$/gm, '<li style="margin-bottom:4px">$1</li>');
      if (p.includes('<li')) p = `<ul style="margin:6px 0 6px 16px;padding:0">${p}</ul>`;
      if (!p.startsWith('<h') && !p.startsWith('<ul')) p = `<p style="margin:0 0 8px;line-height:1.6">${p}</p>`;
      return p;
    })
    .join('\n');

  // Build exhibit index table
  const exhibitRows = opts.exhibits.map(ex =>
    `<tr>
      <td style="padding:4px 8px;border-bottom:1px solid #f3f4f6;font-weight:600;width:60px">Exhibit ${esc(ex.letter)}</td>
      <td style="padding:4px 8px;border-bottom:1px solid #f3f4f6">${esc(ex.name)}</td>
      <td style="padding:4px 8px;border-bottom:1px solid #f3f4f6;font-size:11px;color:#6b7280">${esc(ex.occurredAt ? new Date(ex.occurredAt).toLocaleDateString('en-US') : '')}</td>
    </tr>`,
  ).join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1f2937; font-size: 12px; line-height: 1.45; margin: 0; padding: 0; }
  h1 { font-size: 20px; font-weight: 700; margin: 0 0 4px; color: #111827; }
  .subtitle { color: #6b7280; font-size: 11px; margin-bottom: 16px; }
  .header { text-align: center; margin-bottom: 16px; padding-bottom: 12px; border-bottom: 2px solid #111827; }
  .meta-table td { padding: 3px 0; vertical-align: top; }
  .meta-table td:first-child { color: #6b7280; width: 160px; }
  .meta-table td:last-child { font-weight: 500; }
  .letter-body { font-size: 12px; line-height: 1.6; margin: 16px 0; }
  .exhibit-table { width: 100%; border-collapse: collapse; margin: 8px 0; }
  .exhibit-table th { background: #f9fafb; padding: 6px 8px; text-align: left; font-size: 11px; border-bottom: 1px solid #e5e7eb; }
  .footer { margin-top: 20px; padding-top: 8px; border-top: 1px solid #d1d5db; font-size: 10px; color: #9ca3af; text-align: center; }
</style></head>
<body>

<div class="header">
  <h1>Chargeback Defense Letter</h1>
  <div class="subtitle">
    Generated ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}
    — Document Ref: DP-${esc((opts.defenseId || '').slice(0, 8))}
  </div>
</div>

<table class="meta-table" style="width:100%;margin-bottom:16px">
  <tr><td>Merchant</td><td>${esc(opts.merchantName)}</td></tr>
  <tr><td>Client</td><td>${esc(opts.clientName)}</td></tr>
  <tr><td>Reason Code</td><td>${esc(opts.reasonCode)}</td></tr>
  <tr><td>Disputed Amount</td><td>$${Number(opts.disputeAmount || 0).toFixed(2)}</td></tr>
  <tr><td>Dispute Date</td><td>${esc(opts.disputeDate)}</td></tr>
  ${opts.caseNumber ? `<tr><td>Case/ARN</td><td>${esc(opts.caseNumber)}</td></tr>` : ''}
  <tr><td>Addressee</td><td>${esc(opts.addressee)}</td></tr>
</table>

<div class="letter-body">
${letterHtml}
</div>

${opts.exhibits.length > 0 ? `
<h2 style="font-size:14px;font-weight:600;border-bottom:2px solid #e5e7eb;padding-bottom:4px;margin:20px 0 8px">Exhibit Index</h2>
<table class="exhibit-table">
  <thead><tr><th>Exhibit</th><th>Description</th><th>Date</th></tr></thead>
  <tbody>${exhibitRows}</tbody>
</table>
` : ''}

<div class="footer">
  This defense letter was generated by ScaleSafe. All facts referenced are supported by the exhibits listed above. — ScaleSafe
</div>

</body>
</html>`;
}
