-- 005_storage_bucket.sql — Supabase Storage for PDFs (v2.1)
--
-- File paths:
--   /enrollments/{location_id}/{enrollment_id}.pdf
--   /evidence/{location_id}/{contact_id}.pdf
--   /defense/{location_id}/{defense_packet_id}.pdf
--   /defense/{location_id}/{defense_packet_id}_letter.pdf
--
-- Files are private — accessed via signed URLs generated by the app.

INSERT INTO storage.buckets (id, name, public)
VALUES ('scalesafe-files', 'scalesafe-files', false)
ON CONFLICT (id) DO NOTHING;
