-- 034: Placeholder — evidence table will be added to evidence_timeline view
-- when migration 010 (CREATE TABLE evidence) is applied to the live database.
-- For now, the Clients page queries enrollments directly as a fallback.
